### ISSUE TITLE
Arrow error

### ISSUE THREAD

**Issue by TheJaredWilcurt** [ragingwind/datauri-to-file#3]
I got this error on first use:

![error](https://cloud.githubusercontent.com/assets/4629794/23196908/9e687996-f88a-11e6-94d9-7c18d77ff098.png)

I changed the file to this and the issue went away and worked fine.

```js
'use strict';

const re = require('data-uri-regex');
const mime = require('mime');
const through2 = require('through2');

function toFile (input) {
    return new Promise(function (resolve, reject) {
        if (typeof input !== 'string') {
            return reject(new TypeError('Input should be string as base64'));
        }

        var data = re().exec(input);

        return resolve(data ? {
            mimeType: data[2],
            encoding: data[3],
            data: new Buffer(data[4]),
            extension: mime.extension(data[2])
        } : undefined);
    });
}

module.exports = toFile;

module.exports.stream = function () {
    return through2.obj(function (chunk, enc, cb) {
        var _stream = this;
        toFile(chunk.toString()).then(function (image) {
            _stream.push(image.data);
            cb();
        }).catch(function (err) {
            cb(err);
        });
    });
};
```

The version of Node I'm using cannot be updated for this project.

It seems like such a simple utility library like this should be designed to work as universally as possible. Unless there is a downside to using regular functions over arrow functions, would you consider changing them so I don't need to manually edit files in my `node_modules` folder (which just seems like a terrible idea).

**Comment by ragingwind** [comment]
All of node which are not supported arrow function was deprecated before. Arrow function is now widely used and standard. I can't find any reason for downgrade.

**Comment by TheJaredWilcurt** [comment]
That's cool, it's your project.

For anyone else seeing this with the same issue, I switched over to [base64-img](https://www.npmjs.com/package/base64-img), which is slightly different but worked just the same for what I needed.
