### ISSUE TITLE
data_uri_to_file_1.toFile is not a function

### ISSUE THREAD

**Issue by magicianlee007** [ragingwind/datauri-to-file#5]
I am going to use `data-uri-to-file`package in my angular 4.

> toFile(dataURI).then(file => {
>          console.log(file.mimeType, file.data, file.extension);
> });

But the error shows like this

![screen shot 2017-11-16 at 12 47 09 am](https://user-images.githubusercontent.com/30640392/32842060-d3fcd2be-ca67-11e7-8add-6c6ab2ddc9d5.png)

**Comment by ragingwind** [comment]
Following as error message, toFile is not a function. Check out importing or file existing.

**Comment by magicianlee007** [comment]
`import { toFile } from 'data-uri-to-file';`
I have already import the package and the file exist in the `node_modules`.

**Comment by ragingwind** [comment]
It's basic of using modules, not related to this module, related to your dev environments? did you use it with ts?

**Comment by magicianlee007** [comment]
Yes, I am using TypeScript.
